### ISSUE TITLE
Create Wrapper for current 3pg-model

### ISSUE THREAD

**Issue by qjhart** [CSTARS/pg-poplar-3pg-model#1]
We are making smaller projects from  of our ahb code.  One important component of that is the 3PG model.  Because we use the 3pg model in multiple places, we treat that as a separate library.  To get it to work in postgres, we need a little wrapper code to upload that data into the database, with the proper hooks.  Since the original model, the standard practice for module upload has changed.  Most notable is that we find writing node.js libraries and using [plv8x](https://www.npmjs.com/package/plv8x) to be pretty convenient.

**Comment by hitchpy** [comment]
Sounds fun! We should go over the detail tasks. Maybe tomorrow.

**Comment by qjhart** [comment]
OK, reviewing my notes, I found that using plv8x, I did NOT find convenient.  Actually, we could not get the Livescript component to work with that.  You can see however that the way plv8x is supposed to work is that you can run a plv8x function on any package, and then that package gets uploaded into the code table in the plv8x schema.  Then you can require these directly in your code.  

The example I am thinking of was taken from [ucum.js](https://github.com/jmandel/ucum.js) which I used in postgres for unit conversion.  Instead of using plv8, I just wrote a small wrapper around  the browserified version of this package.  

This wrapper basically included the browswerfied code, and then some small wrapper functions.  The javascript would work (after the init) in other javascript code as well.  You can see this at: 

https://github.com/CSTARS/farm-budgets-data/blob/master/sql/ucum.sql#L4

and you diff that file to the one at: 
https://github.com/jmandel/ucum.js/blob/master/dist/ucum.js

To see the small tweaks I had to do to the ucum.js version. 

We need to decide if plv8x is worth pursuing more, or not, and then work with @jrmerz on the best way to wrap the browwerisfied 3PG code.

**Comment by qjhart** [comment]
Also, We should be able to setup a watcher so we can reinitialize the postgresql functions in postgres whenever the 3pg-model code is tweaked which would help in debugging.

**Comment by jrmerz** [comment]
My 2 cents,

https://github.com/clkao/plv8x is 9+ months w/o update and neither JS expert nor Postgres expert found it easy to use/was able to use it.  @qjhart 's method sounds like a reasonable and clever solution. gets my +1.

I can work on writing a library for performing proper modifications to a module to run inside PG.  This library can have watch capabilities as well.  Thoughts?

**Comment by jrmerz** [comment]
@hitchpy getting Yu Pei involved in discussion.

**Comment by qjhart** [comment]
Agreed.  Let's go that route.
